[package]
name = "assignments"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]

[dependencies]
anyhow = "1.0.45"
clap = "2.33.3"
csv = "1.1.6"
pathfinding = "2.2.2"
